#!/usr/bin/env python3
"""Regenerate docs/LEADERBOARD.md from the verified submissions — no manual editing.

  python harness/build_leaderboard.py --dsn <conninfo>

Scores every `submissions/*.json` by re-running its SQL (harness/score_submission.score),
ranks by the 0-100 Grade (harness/grade), and writes docs/LEADERBOARD.md. This is the only
thing that may write that file: the CI leaderboard job runs it on every push to main and
commits the result, so the published table is always a function of the committed submissions —
never hand-edited. A machine-readable copy is written to submissions/leaderboard.json.
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import psycopg

from harness.grade import compute as compute_grades
from harness.score_submission import score

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = (
    "<!-- AUTO-GENERATED by harness/build_leaderboard.py from submissions/*.json on every push to\n"
    "     main. DO NOT EDIT BY HAND — your changes will be overwritten. To change a number, submit\n"
    "     or update a tool in submissions/ (see CONTRIBUTING.md). -->\n\n"
    "# heron leaderboard — v1 (100 questions, gpt-4o)\n\n"
    "Auto-generated from `submissions/*.json`. **Every metric except token count is recomputed by CI\n"
    "by re-executing each tool's submitted SQL against a freshly-seeded gold database** — accuracy\n"
    "cannot be self-reported. Tokens come from the tool's own `response.usage` (re-runnable via the\n"
    "committed adapter). Ranked by the 0-100 **Grade** ([METHODOLOGY §7](METHODOLOGY.md)); deep-dive\n"
    "+ tool cards in [`CROSS-TOOL-LEADERBOARD.md`](CROSS-TOOL-LEADERBOARD.md).\n\n"
    "> Conditions: `small` scale, 100-question suite, single-state EX@1 @ temp 0, same `gpt-4o` for\n"
    "> every tool. Timing/VES are re-measured by CI on one machine, so they compare tools fairly.\n"
)


def cell(v):
    if v is None:
        return "n/a"
    if isinstance(v, float):
        return f"{v:,.1f}" if v >= 100 else f"{v}"
    return f"{v:,}" if isinstance(v, int) else f"{v}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dsn", required=True)
    ap.add_argument("--out", default=os.path.join(ROOT, "docs", "LEADERBOARD.md"))
    args = ap.parse_args()

    paths = sorted(p for p in glob.glob(os.path.join(ROOT, "submissions", "*.json"))
                   if not p.endswith(".verified.json")
                   and os.path.basename(p) != "leaderboard.json")
    rows, rejected = [], []
    with psycopg.connect(args.dsn) as conn:
        for p in paths:
            sub = json.load(open(p))
            verified, issues = score(sub, conn)
            name = verified.get("tool") or verified.get("adapter") or os.path.basename(p)
            if issues:
                rejected.append((name, issues))
                sys.stderr.write(f"skip {name}: {issues[0]}\n")
                continue
            rows.append(dict(name=name, summary=verified,
                             errs=verified.get("errors", 0), n=verified.get("n")))
    compute_grades(rows)   # attaches grade + dims, sorts by grade

    lines = [HEADER]
    lines.append("| Rank | Tool | Grade | EX@1 | VES | Soft-F1 | Set-Recall | ms/q | tok/q | $/run | errors |")
    lines.append("|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for i, r in enumerate(rows, 1):
        s = r["summary"]
        lines.append(
            f"| {i} | {r['name']} | **{cell(r['grade'])}** | {cell(s.get('ex_at_1'))} | "
            f"{cell(s.get('ves'))} | {cell(s.get('soft_f1'))} | {cell(s.get('set_recall'))} | "
            f"{cell(round(s['avg_total_ms']) if s.get('avg_total_ms') else None)} | "
            f"{cell(round(s['avg_tokens']) if s.get('avg_tokens') else None)} | "
            f"${s.get('est_cost_usd', 0):.2f} | {r['errs']} |")
    lines.append(
        "\n_Grade = .45·EX + .20·EFF(VES) + .10·REL + .15·TOK + .10·LAT (METHODOLOGY §7). EX/VES/"
        "Soft-F1/Set-Recall/errors are **CI-recomputed from each tool's SQL**; tokens are the tool's "
        "self-reported `response.usage`. Submit a tool: see [CONTRIBUTING.md](../CONTRIBUTING.md)._")
    if rejected:
        lines.append("\n**Rejected submissions** (not shown above):")
        for name, issues in rejected:
            lines.append(f"- `{name}` — {issues[0]}")

    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    sys.stderr.write(f"wrote {args.out} ({len(rows)} tools, {len(rejected)} rejected)\n")

    data = {"tools": [{"rank": i, "grade": r["grade"], **r["summary"]}
                      for i, r in enumerate(rows, 1)],
            "rejected": [{"tool": n, "issues": iss} for n, iss in rejected]}
    with open(os.path.join(ROOT, "submissions", "leaderboard.json"), "w") as f:
        json.dump(data, f, indent=2, default=str)


if __name__ == "__main__":
    main()
